-- Step 1: Simplify county geometries, transform to SRID 3857, and get state abbreviations
WITH simplified_counties AS (
    SELECT
        ST_SimplifyPreserveTopology(ST_Transform(c.geom, 3857), 100) AS geom_3857,
        c.namelsad AS county_name,
        s.stusps AS state_abbr
    FROM us_counties c
    JOIN us_states s ON c.statefp = s.statefp
),
-- Step 2: Transform weather stations to SRID 3857 and include state abbreviation
weather_stations_3857 AS (
    SELECT
        ST_Transform(ws.geom, 3857) AS geom,
        ws.station_id,
        ws.state AS state_abbr
    FROM weather_stations ws
),
-- Step 3: Generate Voronoi polygons per state
state_voronoi AS (
    SELECT
        ws.state_abbr,
        (ST_Dump(
            ST_VoronoiPolygons(
                ST_Collect(ws.geom)
            )
        )).geom AS voronoi_geom
    FROM weather_stations_3857 ws
    GROUP BY ws.state_abbr
),
-- Step 4: Associate Voronoi polygons with weather stations
voronoi_with_station AS (
    SELECT
        sv.state_abbr,
        sv.voronoi_geom,
        ws.station_id
    FROM state_voronoi sv
    JOIN weather_stations_3857 ws
      ON ST_Contains(sv.voronoi_geom, ws.geom)
     AND sv.state_abbr = ws.state_abbr
),
-- Step 5: Clip Voronoi polygons with counties
clipped_voronoi AS (
    SELECT
        sc.county_name,
        ST_Intersection(sc.geom_3857, vws.voronoi_geom) AS geom,
        vws.station_id
    FROM simplified_counties sc
    JOIN voronoi_with_station vws
      ON sc.state_abbr = vws.state_abbr
     AND ST_Intersects(sc.geom_3857, vws.voronoi_geom)
    WHERE NOT ST_IsEmpty(ST_Intersection(sc.geom_3857, vws.voronoi_geom))
)
-- Step 6: Create the final table
SELECT
    county_name,
    geom::geometry(MultiPolygon, 3857) AS geom,
    station_id
INTO us_county_weather_stations_voronoi
FROM clipped_voronoi;

-- Step 7: Add primary key
ALTER TABLE us_county_weather_stations_voronoi
ADD COLUMN id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Step 8: Create spatial index
CREATE INDEX idx_us_county_weather_stations_voronoi_geom ON us_county_weather_stations_voronoi USING GIST (geom);
